FROM alpine:latest
LABEL maintainer="robertodelimasouza@gmail.com"

RUN apk add nginx
RUN mkdir -p /run/nginx
RUN touch /run/nginx/nginx.pid
RUN adduser -D -g 'www' www
RUN mkdir /www 
RUN chown -R www:www /var/lib/nginx
RUN chown -R www:www /www

COPY nginx.conf /etc/nginx/nginx.conf
COPY index.html /www

EXPOSE 80

ENTRYPOINT ["nginx"]

CMD ["-g", "daemon off;"]

HEALTHCHECK --timeout=2s CMD curl -f localhost || exit 1